USE [master]
GO

/****** Object:  Database [Ecommerce]    Script Date: 15/12/2016 14:40:03 ******/
CREATE DATABASE [Ecommerce]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Ecommerce', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\Ecommerce.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Ecommerce_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\Ecommerce_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [Ecommerce] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Ecommerce].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Ecommerce] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Ecommerce] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Ecommerce] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Ecommerce] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Ecommerce] SET ARITHABORT OFF 
GO

ALTER DATABASE [Ecommerce] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Ecommerce] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Ecommerce] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Ecommerce] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Ecommerce] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Ecommerce] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Ecommerce] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Ecommerce] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Ecommerce] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Ecommerce] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Ecommerce] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Ecommerce] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Ecommerce] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Ecommerce] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Ecommerce] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Ecommerce] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Ecommerce] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Ecommerce] SET RECOVERY FULL 
GO

ALTER DATABASE [Ecommerce] SET  MULTI_USER 
GO

ALTER DATABASE [Ecommerce] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Ecommerce] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Ecommerce] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Ecommerce] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [Ecommerce] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Ecommerce] SET  READ_WRITE 
GO


USE [Ecommerce]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE TABLE [dbo].[Categorie](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[nom_categorie] [nchar](50) NOT NULL,
	[image] [nchar](200) NULL,
	[description] [ntext] NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

CREATE TABLE [dbo].[Client](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[nom] [nchar](40) NOT NULL,
	[prenom] [nchar](40) NOT NULL,
	[email] [nchar](40) NOT NULL,
	[genre] [nchar](3) NOT NULL,
	[mot_de_passe] [nchar](100) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

CREATE TABLE [dbo].[Commande](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[id_utilisateur] [int] NOT NULL,
	[etat] [nchar](10) NOT NULL,
	[date_commande] [nchar](20) NULL,
	[date_livraison] [nchar](20) NULL,
	[date_expedition] [nchar](20) NULL,
	[id_livraison] [int] NOT NULL,
	[fret] [nchar](10) NOT NULL,
	[id_methode_livraison] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

CREATE TABLE [dbo].[Detail_commande](
	[id_commande] [int] NOT NULL,
	[id_produit] [int] NOT NULL,
	[prix_unit] [nchar](20) NOT NULL,
	[quantite] [int] NOT NULL,
 CONSTRAINT [pk_DetailId] PRIMARY KEY CLUSTERED 
(
	[id_commande] ASC,
	[id_produit] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

CREATE TABLE [dbo].[Methode_de_livraison](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[nom] [nchar](70) NOT NULL,
	[description] [ntext] NULL,
	[prix] [nchar](20) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

CREATE TABLE [dbo].[Panier](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[id_client] [int] NOT NULL,
	[id_produit] [int] NOT NULL,
	[quantite] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

CREATE TABLE [dbo].[Produit](
	[id] [bigint] IDENTITY(1,1) NOT NULL,
	[nom_produit] [nchar](40) NOT NULL,
	[id_categorie] [bigint] NOT NULL,
	[prix] [nchar](20) NOT NULL,
	[image] [nchar](200) NULL,
	[description] [ntext] NULL,
	[stock] [bigint] NOT NULL,
	[quantite_lots] [int] NOT NULL,
	[niveau_reapprovisionnement] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO